# Generated by Django 5.1.2 on 2024-10-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_rename_img_post_imgage_name_alter_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='imgage_name',
        ),
        migrations.AddField(
            model_name='post',
            name='imgage',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
