# Generated by Django 5.1.2 on 2024-10-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_remove_post_imgage_name_post_imgage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgage',
            new_name='image',
        ),
    ]
